'use client';
import {useEffect,useState,useCallback} from 'react';
import {ArrowUpRight,Bell,MapPin,ArrowRight,Check,RotateCw} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Toaster} from '@/components/ui/sonner';
import {toast} from 'sonner';
import {Choice,Modal,Empty} from '@/components/sixpaths/shared';
import {Browse} from '@/components/sixpaths/browse';
import {Calculators} from '@/components/sixpaths/calculators';
import {Workspace} from '@/components/sixpaths/workspace';
import {makeInitialData,type AppData,type Role,shortDate} from '@/lib/model';
export default function Home(){
 const [view,setView]=useState('browse'),[city,setCity]=useState('Kaduna'),[role,setRole]=useState<Role>('Owner'),[data,setData]=useState<AppData>(()=>makeInitialData()),[revision,setRevision]=useState(0),[ready,setReady]=useState(false),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notifications,setNotifications]=useState(false),[price,setPrice]=useState(25000000);
 const load=useCallback(async()=>{setLoading(true);setError('');try{const r=await fetch('/api/workspace');const body=await r.json() as {data:AppData;revision:number;error?:string};if(!r.ok)throw new Error(body.error);setData(body.data);setRevision(body.revision);setReady(true)}catch(e){setError(e instanceof Error?e.message:'Your workspace could not be loaded.');setReady(false)}finally{setLoading(false)}},[]);
 useEffect(()=>{load();const hash=window.location.hash.slice(1);if(['browse','calculators','workspace'].includes(hash))setView(hash);const handler=()=>{const v=window.location.hash.slice(1);setView(['browse','calculators','workspace'].includes(v)?v:'browse')};window.addEventListener('hashchange',handler);return()=>window.removeEventListener('hashchange',handler)},[load]);
 function navigate(v:string){setView(v);window.location.hash=v;window.scrollTo({top:0,behavior:'smooth'})}
 async function mutate(action:Record<string,unknown>){
  if(!ready||busy)return false;setBusy(true);setError('');
  try{const r=await fetch('/api/workspace',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision,action})});const body=await r.json() as {data:AppData;revision:number;error?:string};if(!r.ok){if(r.status===409)await load();throw new Error(body.error||'Your changes could not be saved.')};setData(body.data);setRevision(body.revision);toast.success(action.type==='readNotifications'?'All caught up':'Saved to your workspace');return true}
  catch(e){const message=e instanceof Error?e.message:'Your changes could not be saved. Please try again.';toast.error(message);return false}
  finally{setBusy(false)}
 }
 const unread=data.notifications.filter(n=>!n.read).length;
 return <><a className="skip-link" href="#main-content">Skip to content</a><header className="site-header"><div className="header-inner"><a className="brand" href="#browse" onClick={()=>navigate('browse')} aria-label="Six Paths home"><img src="/brand.png" alt=""/><span>Six Paths<small>SMART-HOUSE</small></span></a><nav className="main-nav" aria-label="Main navigation"><button className={view==='browse'?'active':''} onClick={()=>navigate('browse')}>Browse homes</button><button className={view==='calculators'?'active':''} onClick={()=>navigate('calculators')}>Financial tools</button><button className={view==='workspace'?'active':''} onClick={()=>navigate('workspace')}>My workspace</button></nav><div className="header-actions"><div className="header-city"><MapPin size={16}/><Choice label="Choose a city" value={city} options={['Kaduna','Lagos','Abuja','Kano']} onChange={v=>{setCity(v);navigate('browse')}}/></div><Button variant="ghost" className="bell-button" aria-label={`Notifications, ${unread} unread`} onClick={()=>setNotifications(true)}><Bell size={20}/>{ready&&unread>0&&<span/>}</Button><Button className="workspace-button" onClick={()=>navigate('workspace')}>Your workspace <ArrowUpRight size={16}/></Button></div></div></header>
 {error&&<div role="alert" className="load-error"><span>{error}</span><Button variant="outline" size="sm" disabled={loading} onClick={load}><RotateCw size={14}/>Try again</Button></div>}
 <div id="main-content">{view==='browse'?<Browse data={data} city={city} onCity={setCity} onCalculate={p=>{setPrice(p);navigate('calculators')}} mutate={mutate} busy={busy} ready={ready}/>:view==='calculators'?<Calculators key={price} initialPrice={price}/>:loading?<main className="page"><Empty title="Opening your workspace…"/></main>:!ready?<main className="page"><Empty title="Your workspace is unavailable"><p>Try again to load your saved properties and repairs.</p><Button onClick={load}>Reload workspace</Button></Empty></main>:<Workspace data={data} role={role} setRole={setRole} mutate={mutate} busy={busy} ready={ready} onBrowse={()=>navigate('browse')}/>}</div>
 <footer className="site-footer"><a className="footer-brand" href="#browse" onClick={()=>navigate('browse')}><img src="/brand.png" alt=""/><span>Six Paths Smart-House</span></a><p>Find a home. Make it yours.</p></footer>
 <Modal open={notifications} onClose={()=>setNotifications(false)} title="Your updates" description="Activity across your private workspace.">{ready?<><div className="notification-toolbar"><span>{unread} unread</span><Button variant="link" disabled={busy||!unread} onClick={()=>mutate({type:'readNotifications'})}><Check size={15}/>Mark all read</Button></div>{data.notifications.length?<div className="notification-list">{data.notifications.map(n=><div className={'notification '+(!n.read?'unread':'')} key={n.id}><span><Bell size={16}/></span><div><p>{n.text}</p><small>{shortDate(n.date)}</small></div></div>)}</div>:<Empty title="All caught up"/>}</>:<p>Load your workspace to see saved updates.</p>}</Modal><Toaster position="bottom-right" richColors theme="light"/></>
}
