'use client';
import {useMemo,useState} from 'react';
import {Search,SlidersHorizontal,ArrowUpRight,MapPin,BedDouble,Bath,MoveUpRight,Maximize,Check,Leaf,Sparkles,ArrowRight,Building2} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Checkbox} from '@/components/ui/checkbox';
import {Progress} from '@/components/ui/progress';
import {Choice,Modal,Field,Status,Empty,Submit,type Mutation} from './shared';
import {type AppData,type Property,money} from '@/lib/model';
const areas=['All areas','Barnawa','Kawo','Malali','Ungwan Rimi','Sabon Tasha'];
export function Browse({data,city,onCity,onCalculate,mutate,busy,ready}:{data:AppData;city:string;onCity:(s:string)=>void;onCalculate:(p:number)=>void;mutate:Mutation;busy:boolean;ready:boolean}){
 const [query,setQuery]=useState(''),[search,setSearch]=useState(''),[area,setArea]=useState('All areas'),[budget,setBudget]=useState('any'),[beds,setBeds]=useState('any'),[tab,setTab]=useState('all'),[sort,setSort]=useState('featured');
 const [filters,setFilters]=useState(false),[solar,setSolar]=useState(false),[gated,setGated]=useState(false),[smart,setSmart]=useState(false),[smartText,setSmartText]=useState('');
 const [selected,setSelected]=useState<Property|null>(null),[interest,setInterest]=useState(false),[sent,setSent]=useState(false),[contact,setContact]=useState({name:'',email:'',phone:'',note:''});
 const available=data.properties.filter(p=>p.status==='Available'&&p.rent>0);
 const found=useMemo(()=>{
  const q=search.toLowerCase().trim();
  return available.filter(p=>(area==='All areas'||p.area===area)&&(budget==='any'||p.rent<=Number(budget))&&(beds==='any'||p.beds>=Number(beds))&&(tab!=='rto'||p.rto)&&(tab!=='construction'||p.stage==='Under construction')&&(!solar||p.amenities.includes('Solar power'))&&(!gated||p.amenities.includes('Gated compound'))&&(!q||`${p.title} ${p.address} ${p.description} ${p.amenities.join(' ')}`.toLowerCase().includes(q))).sort((a,b)=>sort==='low'?a.rent-b.rent:sort==='high'?b.rent-a.rent:0);
 },[available,area,budget,beds,tab,solar,gated,search,sort]);
 const reset=()=>{setQuery('');setSearch('');setArea('All areas');setBudget('any');setBeds('any');setSolar(false);setGated(false);setTab('all')};
 function smartSearch(){
  const q=smartText.toLowerCase();const place=areas.slice(1).find(a=>q.includes(a.toLowerCase()));
  const bed=q.match(/(\d+)\s*(?:bed|br)/);const amount=q.match(/(?:under|below|budget|up to|max)\s*[₦n]?\s*([\d,.]+)\s*(k|m|million|thousand)?/);
  reset();if(place)setArea(place);if(bed)setBeds(String(Math.min(4,Number(bed[1]))));
  if(amount){let n=Number(amount[1].replaceAll(',',''));if(['k','thousand'].includes(amount[2]))n*=1000;if(['m','million'].includes(amount[2]))n*=1000000;setBudget(String(n));}
  else if(q.includes('cheap')||q.includes('affordable'))setBudget('100000');
  setSolar(q.includes('solar'));setGated(q.includes('gated'));if(/rent.?to.?own/.test(q))setTab('rto');else if(q.includes('construction'))setTab('construction');
  if(!place&&!bed&&!amount&&!/solar|gated|cheap|affordable|rent.?to.?own|construction/.test(q)){setSearch(smartText);setQuery(smartText)}
  setSmart(false);
 }
 async function submitInterest(e:React.FormEvent){e.preventDefault();if(selected&&await mutate({type:'interest',propertyId:selected.id,...contact}))setSent(true)}
 const extra=Number(solar)+Number(gated);
 const budgetOptions=[{value:'any',label:'Any budget'},...['100000','150000','250000','400000','600000'].map(v=>({value:v,label:`Up to ${money(Number(v))}`}))];
 if(!budgetOptions.some(o=>o.value===budget))budgetOptions.push({value:budget,label:`Up to ${money(Number(budget))}`});
 return <main className="page browse-page">
 <div className="browse-heading"><div><p className="eyebrow"><span className="tiny-line"/> A PLACE FOR YOUR NEXT CHAPTER</p><h1>Find your next <em>home.</em></h1><p>Good homes. Clear choices. A little closer to where you belong.</p></div><div className="city-caption"><MapPin size={17}/><div><strong>{city}, Nigeria</strong><span>{city==='Kaduna'?'Explore the collection':'Coming soon'}</span></div></div></div>
 <section className="search-bar" aria-label="Search homes"><form onSubmit={e=>{e.preventDefault();setSearch(query)}}><div className="search-field"><Search size={21}/><Input aria-label="Search by street or area" placeholder="Search by street or area" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="filter-field"><span>LOCATION</span><Choice label="Locality" value={area} onChange={setArea} options={areas}/></div><div className="filter-field"><span>MONTHLY BUDGET</span><Choice label="Monthly budget" value={budget} onChange={setBudget} options={budgetOptions}/></div><div className="filter-field beds-filter"><span>BEDROOMS</span><Choice label="Bedrooms" value={beds} onChange={setBeds} options={[{value:'any',label:'Any beds'},...['1','2','3','4'].map(v=>({value:v,label:`${v}+ beds`}))]}/></div><Button type="submit" className="search-button"><Search size={18}/><span>Search</span></Button></form></section>
 {city==='Kaduna'?<>
 <div className="discovery-bar"><Tabs value={tab} onValueChange={setTab}><TabsList className="browse-tabs"><TabsTrigger value="all">All homes <span>{available.length}</span></TabsTrigger><TabsTrigger value="rto">Rent-to-own</TabsTrigger><TabsTrigger value="construction">Under construction</TabsTrigger></TabsList></Tabs><Button variant="outline" className="filter-button" onClick={()=>setFilters(true)}><SlidersHorizontal size={16}/>More filters{extra>0&&` (${extra})`}</Button></div>
 <div className="browse-layout"><section className="listings"><div className="listing-heading"><h2>{search?'Search results':tab==='rto'?'A path to ownership':tab==='construction'?'Make room for what’s next':'Homes to make your own'}<span>{found.length} {found.length===1?'home':'homes'}</span></h2><Choice label="Sort homes" value={sort} onChange={setSort} options={[{value:'featured',label:'Recommended'},{value:'low',label:'Price: low to high'},{value:'high',label:'Price: high to low'}]}/></div>
 {found.length?<div className="property-grid">{found.map((p,i)=><button key={p.id} className="property-card" onClick={()=>{setSelected(p);setInterest(false);setSent(false)}}><div className="property-photo">{p.image?<img src={p.image} alt={`${p.beds}-bedroom home in ${p.area}`} loading={i<3?'eager':'lazy'}/>:<div className="no-photo"><Building2 size={35}/><span>Photo not provided</span></div>}<div className="photo-badges"><span className={'photo-status '+(p.stage==='Under construction'?'construction':'')}>{p.stage==='Under construction'?'Under construction':'Available'}</span>{p.rto&&<span className="rto-badge"><Leaf size={12}/> Rent-to-own</span>}</div><span className="card-open"><ArrowUpRight size={18}/></span></div><div className="property-content"><p className="property-location"><MapPin size={13}/>{p.area}, Kaduna</p><h3>{p.title}</h3><div className="property-specs"><span><BedDouble size={16}/>{p.beds} beds</span><span><Bath size={16}/>{p.baths} baths</span><span><Maximize size={14}/>{p.size} m²</span></div><div className="property-bottom"><div><strong>{money(p.rent)}</strong><span> / month</span></div><span>{p.stage==='Under construction'?`${p.progress}% built`:'View home'} <ArrowRight size={14}/></span></div></div></button>)}</div>:<Empty title="No homes match just yet"><p>Try a different area, budget or bedroom count.</p><Button variant="outline" onClick={reset}>Clear filters</Button></Empty>}
 <p className="collection-note">Listings from the Six Paths collection. Photos and prices are up to date.</p>
 </section><aside className="discovery-aside"><div className="smart-card"><span className="smart-icon"><Sparkles size={25}/></span><p className="eyebrow">A MORE PERSONAL SEARCH</p><h2>Your kind<br/>of home.</h2><p>Tell us the area, budget and little details that matter to you.</p><div className="prompt-example">“3 bedrooms in Kawo under ₦400k with solar power”</div><Button onClick={()=>setSmart(true)}>Try Smart Search <ArrowUpRight size={17}/></Button><small>Matches your words to listing filters.</small></div><div className="planning-card"><span className="round-icon"><Building2 size={21}/></span><h3>Rent today.<br/>Own tomorrow.</h3><p>See what a rent-to-own plan could look like for you.</p><Button variant="link" onClick={()=>onCalculate(25000000)}>Explore the numbers <ArrowRight size={16}/></Button></div><div className="assurance"><Check size={17}/><p>Property details, repairs and payments. All in one place.</p></div></aside></div>
 </>:<Empty title={`Six Paths is coming to ${city}`}><p>Kaduna is the app’s current pilot city.</p><Button onClick={()=>onCity('Kaduna')}>Browse Kaduna homes</Button></Empty>}
 <Modal open={filters} onClose={()=>setFilters(false)} title="A few more details" description="Find the features that matter to you."><label className="check-row"><Checkbox checked={solar} onCheckedChange={v=>setSolar(v===true)}/><span>Solar power</span><Leaf size={18}/></label><label className="check-row"><Checkbox checked={gated} onCheckedChange={v=>setGated(v===true)}/><span>Gated compound</span></label><div className="dialog-actions"><Button variant="ghost" onClick={()=>{setSolar(false);setGated(false)}}>Clear</Button><Button onClick={()=>setFilters(false)}>Show {found.length} homes</Button></div></Modal>
 <Modal open={smart} onClose={()=>setSmart(false)} title="Describe your kind of home" description="Include a locality, monthly budget, bedrooms, solar power, or rent-to-own."><form onSubmit={e=>{e.preventDefault();smartSearch()}} className="stack"><Textarea required rows={4} maxLength={500} value={smartText} onChange={e=>setSmartText(e.target.value)} placeholder="3 bedroom rent-to-own home in Kawo under 400k with solar power"/><div className="suggestions">{['3 bedrooms in Barnawa','Cheap apartment with prepaid meter','Rent-to-own with solar power'].map(s=><Button variant="outline" type="button" key={s} onClick={()=>setSmartText(s)}>{s}</Button>)}</div><Button type="submit">Find matching homes <Search size={16}/></Button></form></Modal>
 <Modal open={!!selected} onClose={()=>setSelected(null)} title={interest?'Interested in this home?':selected?.title||'Home details'} description={selected?.address} wide={!interest}>
 {selected&&(interest?<>{sent?<div className="success-state"><span><Check size={30}/></span><h3>Interest saved</h3><p>Your request is saved in the Admin workspace under Interest requests.</p><Button onClick={()=>setSelected(null)}>Back to homes</Button></div>:<form onSubmit={submitInterest} className="stack"><p className="notice">Request · This saves your interest in your private workspace.</p><Field label="Full name"><Input required maxLength={200} value={contact.name} onChange={e=>setContact({...contact,name:e.target.value})}/></Field><div className="form-grid"><Field label="Email"><Input required type="email" maxLength={200} value={contact.email} onChange={e=>setContact({...contact,email:e.target.value})}/></Field><Field label="Phone number"><Input required type="tel" minLength={7} maxLength={30} value={contact.phone} onChange={e=>setContact({...contact,phone:e.target.value})}/></Field></div><Field label="Anything else? (optional)"><Textarea maxLength={2000} value={contact.note} onChange={e=>setContact({...contact,note:e.target.value})}/></Field><Submit busy={busy||!ready}>Save interest</Submit></form>}</>:<div className="property-detail">{selected.image?<img className="detail-photo" src={selected.image} alt={`Sample property in ${selected.area}`}/>:<div className="no-photo detail-photo"><Building2 size={40}/><span>Photo not provided</span></div>}<div className="detail-info"><div className="detail-main"><div className="inline"><Status>{selected.stage}</Status>{selected.rto&&<span className="status green">Rent-to-own eligible</span>}</div><div className="property-specs"><span><BedDouble size={18}/>{selected.beds} bedrooms</span><span><Bath size={18}/>{selected.baths} bathrooms</span><span><Maximize size={16}/>{selected.size} m²</span></div><h3>About this home</h3><p>{selected.description}</p><h3>The little details</h3><div className="amenity-grid">{selected.amenities.map(a=><span key={a}><Check size={15}/>{a}</span>)}</div><h3>Floor plan</h3><p>{selected.floorPlan}</p>{selected.stage==='Under construction'&&<div className="stack"><p>Construction progress · {selected.progress}%</p><Progress value={selected.progress}/></div>}</div><div className="detail-price"><span>Monthly rent</span><strong>{money(selected.rent)}</strong><p>Featured listing. Availability and price are up to date.</p><Button disabled={!ready} onClick={()=>setInterest(true)}>Express interest <MoveUpRight size={16}/></Button>{selected.rto&&<Button variant="outline" onClick={()=>{setSelected(null);onCalculate(selected.price)}}>Estimate rent-to-own</Button>}</div></div></div>)}
 </Modal></main>
}
