'use client';
import {useState} from 'react';
import {Building2,Plus,ArrowUpRight,ArrowRight,Wrench,Wallet,House,Check,Clock,MapPin,Star,ShieldCheck,ChevronRight,FileText,Users,Settings,Inbox} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Switch} from '@/components/ui/switch';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Table,TableHeader,TableRow,TableHead,TableBody,TableCell} from '@/components/ui/table';
import {Choice,Field,NumberField,Modal,Status,Empty,Submit,type Mutation} from './shared';
import {type AppData,type Role,type Property,type Repair,personas,money,shortDate} from '@/lib/model';
const navs:Record<Role,string[]>={Owner:['Overview','Properties','Repairs','Payments'],Tenant:['Overview','My reports','Payments'],Provider:['New jobs','Bookings','Earnings','Profile'],Admin:['Overview','Properties','Repair queue','Interest requests','Providers','Users','Payments','Platform rates']};
const blankProperty:Property={id:'',title:'',address:'',area:'Barnawa',city:'Kaduna',rent:150000,beds:3,baths:2,size:200,status:'Available',stage:'Ready to move in',progress:100,rto:false,price:25000000,amenities:[],description:'',image:'',year:2026,warranty:'',floorPlan:''};
export function Workspace({data,role,setRole,mutate,busy,ready,onBrowse}:{data:AppData;role:Role;setRole:(r:Role)=>void;mutate:Mutation;busy:boolean;ready:boolean;onBrowse:()=>void}){
 const [tab,setTab]=useState(navs[role][0]),[property,setProperty]=useState<Property|null>(null),[repairId,setRepairId]=useState<string|null>(null),[report,setReport]=useState(false),[billId,setBillId]=useState<string|null>(null);
 const [reportForm,setReportForm]=useState({propertyId:'p6',category:'Plumbing',urgency:'Normal',description:'',providerId:''}),[providerId,setProviderId]=useState(''),[visit,setVisit]=useState('Tomorrow, morning');
 const [repairFilter,setRepairFilter]=useState('All statuses'),[propQuery,setPropQuery]=useState('');
 const [rates,setRates]=useState(data.rates);
 const pFor=(id:string)=>data.properties.find(p=>p.id===id);
 const currentRepair=data.repairs.find(r=>r.id===repairId),currentBill=data.payments.find(p=>p.id===billId);
 const repairs=role==='Tenant'?data.repairs.filter(r=>r.propertyId==='p6'):role==='Provider'?data.repairs.filter(r=>r.providerId==='v1'):data.repairs;
 const payments=role==='Tenant'?data.payments.filter(p=>p.propertyId==='p6'):data.payments;
 const due=payments.filter(p=>p.status==='Due');
 const open=repairs.filter(r=>!['Confirmed','Closed'].includes(r.status));
 const completed=repairs.filter(r=>r.status==='Confirmed');
 const earned=completed.reduce((n,r)=>n+r.amount,0);
 const blocked=busy||!ready;
 const changeRole=(r:string)=>{setRole(r as Role);setTab(navs[r as Role][0]);setRepairFilter('All statuses')};
 async function saveProperty(e:React.FormEvent){e.preventDefault();if(property&&await mutate({type:'property',property:{...property,amenities:property.amenities.filter(a=>a.trim())}}))setProperty(null)}
 async function saveReport(e:React.FormEvent){e.preventDefault();if(await mutate({type:'report',...reportForm,reportedBy:role==='Tenant'?'Tenant':role==='Admin'?'Admin':'Owner'})){setReport(false);setReportForm({...reportForm,description:'',providerId:''});setTab(role==='Tenant'?'My reports':role==='Admin'?'Repair queue':'Repairs')}}
 async function repairAction(status:string){if(currentRepair)await mutate({type:'repair',id:currentRepair.id,status,...(status==='Offered'?{providerId}:{}),...(status==='Scheduled'?{window:visit}:{})})}
 const openRepair=(r:Repair)=>{setRepairId(r.id);setProviderId(data.providers.find(p=>p.status==='Verified'&&p.trade===r.category)?.id||'')};
 function RepairList({items}:{items:Repair[]}){return items.length?<div className="repair-list">{items.map(r=><button key={r.id} className="repair-row" onClick={()=>openRepair(r)}><span className={'repair-icon '+(r.urgency==='Urgent'?'urgent':'')}><Wrench size={20}/></span><div><div className="inline"><strong>{r.category} repair</strong>{r.urgency==='Urgent'&&<span className="urgent-text">Urgent</span>}</div><span>{pFor(r.propertyId)?.address}</span><p>{r.description}</p></div><div className="repair-row-status"><Status>{r.status}</Status><ChevronRight size={18}/></div></button>)}</div>:<Empty title="All caught up"><p>No repairs in this view.</p></Empty>}
 function PaymentTable({items}:{items:AppData['payments']}){return items.length?<Table><TableHeader><TableRow><TableHead>Payment</TableHead><TableHead>Property</TableHead><TableHead>Date</TableHead><TableHead>Amount</TableHead><TableHead>Status</TableHead><TableHead><span className="sr-only">Action</span></TableHead></TableRow></TableHeader><TableBody>{items.map(p=><TableRow key={p.id}><TableCell><strong>{p.label}</strong><small>{p.type}</small></TableCell><TableCell>{pFor(p.propertyId)?.area}</TableCell><TableCell>{shortDate(p.date)}</TableCell><TableCell>{money(p.amount)}</TableCell><TableCell><Status>{p.status}</Status></TableCell><TableCell>{p.status==='Due'&&<Button size="sm" variant="outline" disabled={blocked} onClick={()=>setBillId(p.id)}>Pay bill</Button>}</TableCell></TableRow>)}</TableBody></Table>:<Empty title="No payments yet"><p>Recorded payments will appear here.</p></Empty>}
 const propertyList=data.properties.filter(p=>`${p.title} ${p.address}`.toLowerCase().includes(propQuery.toLowerCase()));
 return <main className="page workspace-page"><div className="workspace-heading"><div><p className="eyebrow">YOUR WORKSPACE</p><h1>{role==='Admin'?'The bigger picture.':role==='Provider'?'Good work starts here.':`Welcome back, ${personas[role].name.split(' ')[0]}.`}</h1><p>{personas[role].description}</p></div><div className="role-select"><span className="avatar">{personas[role].initials}</span><div><span>Select role</span><Choice label="Workspace role" value={role} onChange={changeRole} options={Object.keys(personas)}/></div></div></div>
 <div className="demo-notice"><ShieldCheck size={17}/><span>Workspace · Records · Payments managed directly</span></div>
 <Tabs value={tab} onValueChange={setTab}><TabsList className="workspace-tabs">{navs[role].map(n=><TabsTrigger value={n} key={n}>{n}{n==='Interest requests'&&data.interests.filter(i=>i.status==='New').length>0&&<span className="count">{data.interests.filter(i=>i.status==='New').length}</span>}</TabsTrigger>)}</TabsList></Tabs>
 {tab==='Overview'&&<>
 <div className="metric-grid">{(role==='Tenant'?[{label:'Your home',value:pFor('p6')?.area||'Malali',icon:House,sub:'14 Ali Akilu Road'},{label:'Open reports',value:open.length,icon:Wrench,sub:'Repairs being looked after'},{label:'Bills to settle',value:money(due.reduce((n,p)=>n+p.amount,0)),icon:Wallet,sub:`${due.length} outstanding bills`}]:[{label:'Properties',value:data.properties.length,icon:Building2,sub:`${data.properties.filter(p=>p.status==='Available').length} available · ${data.properties.filter(p=>p.status==='Occupied').length} occupied`},{label:'Open repairs',value:open.length,icon:Wrench,sub:`${repairs.filter(r=>r.status==='Awaiting confirmation').length} awaiting confirmation`},{label:role==='Admin'?'New interest requests':'Bills to settle',value:role==='Admin'?data.interests.filter(i=>i.status==='New').length:money(due.reduce((n,p)=>n+p.amount,0)),icon:role==='Admin'?Inbox:Wallet,sub:role==='Admin'?'From the home collection':`${due.length} outstanding bills`}]).map(m=><div className="metric" key={m.label}><div><span>{m.label}</span><m.icon size={20}/></div><strong>{m.value}</strong><p>{m.sub}</p></div>)}</div>
 <div className="overview-grid"><section className="panel"><div className="section-title"><h2>{role==='Tenant'?'Your recent reports':'Repairs to keep an eye on'}</h2><Button variant="link" onClick={()=>setTab(role==='Tenant'?'My reports':role==='Admin'?'Repair queue':'Repairs')}>View all <ArrowRight size={16}/></Button></div><RepairList items={open.slice(0,3)}/></section><aside className="workspace-actions"><h2>A little housekeeping</h2><Button variant="outline" onClick={()=>{setReport(true);setReportForm({...reportForm,propertyId:'p6',providerId:''})}}><Wrench size={20}/><span>Report an issue<small>Get the right help for your home</small></span><ArrowUpRight size={17}/></Button><Button variant="outline" onClick={()=>setTab('Payments')}><Wallet size={20}/><span>Pay a bill<small>Review your outstanding bills</small></span><ArrowUpRight size={17}/></Button>{role!=='Tenant'&&<Button variant="outline" onClick={()=>setProperty({...blankProperty})}><Plus size={20}/><span>Add a property<small>Keep your portfolio in one place</small></span><ArrowUpRight size={17}/></Button>}{role==='Tenant'&&<Button variant="outline" onClick={onBrowse}><House size={20}/><span>Browse homes<small>Find your next chapter</small></span><ArrowUpRight size={17}/></Button>}</aside></div>
 {role==='Tenant'&&<div className="panel tenant-home"><img src={pFor('p6')?.image} alt="Sample home in Malali"/><div><p className="eyebrow">YOUR HOME</p><h2>14 Ali Akilu Road</h2><p>Malali, Kaduna</p><Status>Occupied</Status><div className="inline"><span>3 bedrooms</span><span>2 bathrooms</span><strong>{money(pFor('p6')?.rent||0)} / month</strong></div></div></div>}
 </>}
 {tab==='Properties'&&<section><div className="section-title"><h2>Your portfolio <span className="muted">{data.properties.length}</span></h2><Button disabled={blocked} onClick={()=>setProperty({...blankProperty})}><Plus size={17}/>Add property</Button></div><Input className="portfolio-search" placeholder="Search by street or area" aria-label="Search properties" value={propQuery} onChange={e=>setPropQuery(e.target.value)}/><div className="portfolio-list">{propertyList.map(p=><article className="portfolio-row" key={p.id}><div className="portfolio-photo">{p.image?<img src={p.image} alt={`Sample home in ${p.area}`}/>:<Building2 size={30}/>}</div><div><p>{p.area.toUpperCase()}</p><h3>{p.title}</h3><span>{p.address}</span><div className="inline"><Status>{p.status}</Status><span>{p.beds} beds · {p.baths} baths</span></div></div><div className="portfolio-rent"><strong>{money(p.rent)}</strong><span>per month</span><Button variant="outline" disabled={blocked} onClick={()=>setProperty({...p})}>Manage property <ArrowUpRight size={15}/></Button></div></article>)}</div>{!propertyList.length&&<Empty title="No matching properties"/>}</section>}
 {['Repairs','My reports','Repair queue','New jobs','Bookings'].includes(tab)&&<section><div className="section-title"><h2>{tab==='New jobs'?'Your next opportunity':tab}</h2>{role!=='Provider'&&<Button disabled={blocked} onClick={()=>setReport(true)}><Plus size={17}/>Report an issue</Button>}</div>{role!=='Provider'&&<div className="filter-toolbar"><Choice label="Filter repair status" value={repairFilter} onChange={setRepairFilter} options={['All statuses','Reported','Offered','Scheduled','Awaiting confirmation','Confirmed','Closed']}/></div>}<div className="panel"><RepairList items={repairs.filter(r=>tab==='New jobs'?r.status==='Offered':tab==='Bookings'?r.status!=='Offered':repairFilter==='All statuses'||r.status===repairFilter)}/></div></section>}
 {tab==='Payments'&&<section><div className="section-title"><div><h2>One place for every payment</h2><p className="muted">Utility and repair payments for your properties.</p></div></div><div className="payment-summary"><Wallet size={25}/><div><span>Outstanding bills</span><strong>{money(due.reduce((n,p)=>n+p.amount,0))}</strong></div><span>{due.length} to settle</span></div><div className="panel"><PaymentTable items={payments}/></div><p className="fine-print">Payments update the workspace ledger.</p></section>}
 {tab==='Earnings'&&<section><div className="metric-grid"><div className="metric"><span>Total earnings</span><strong>{money(earned)}</strong><p>Confirmed jobs</p></div><div className="metric"><span>Awaiting confirmation</span><strong>{money(repairs.filter(r=>r.status==='Awaiting confirmation').reduce((n,r)=>n+r.amount,0))}</strong><p>Waiting for the property owner</p></div><div className="metric"><span>Jobs completed</span><strong>{completed.length}</strong><p>In this workspace</p></div></div><div className="panel"><div className="section-title"><h2>Completed jobs</h2></div><RepairList items={completed}/></div><p className="fine-print">Earnings update automatically upon job confirmation.</p></section>}
 {tab==='Profile'&&<div className="panel provider-profile"><span className="avatar large">BO</span><h2>Bola Okafor</h2><p>Plumbing · Kaduna</p><Status>{data.providers[0].status}</Status><div className="provider-stats"><span><Star size={18}/>{data.providers[0].rating} rating</span><span><Wrench size={18}/>{data.providers[0].jobs} jobs</span></div><hr/><h3>Verification</h3><p>ID and references are marked verified.</p><h3>Payout account</h3><p>Payout account status active.</p></div>}
 {tab==='Interest requests'&&<section><div className="section-title"><h2>Interest requests</h2><span className="muted">{data.interests.length} total</span></div>{data.interests.length?<div className="interest-list">{data.interests.map(i=><article className="panel interest-card" key={i.id}><div><Status>{i.status}</Status><span>{shortDate(i.createdAt)}</span></div><h3>{i.name}</h3><p>{pFor(i.propertyId)?.address}</p><dl><dt>Email</dt><dd>{i.email}</dd><dt>Phone</dt><dd>{i.phone}</dd></dl>{i.note&&<p className="quote">{i.note}</p>}<div className="inline">{i.status==='New'&&<Button variant="outline" disabled={blocked} onClick={()=>mutate({type:'interestStatus',id:i.id,status:'Contacted'})}>Mark contacted</Button>}{i.status!=='Closed'&&<Button variant="ghost" disabled={blocked} onClick={()=>mutate({type:'interestStatus',id:i.id,status:'Closed'})}>Close request</Button>}</div></article>)}</div>:<Empty title="No interest requests yet"><p>Requests saved from the home collection appear here.</p><Button variant="outline" onClick={onBrowse}>Browse homes</Button></Empty>}</section>}
 {tab==='Providers'&&<section><div className="section-title"><h2>Repair providers</h2><span className="muted">{data.providers.filter(p=>p.status==='Under review').length} awaiting review</span></div><div className="provider-grid">{data.providers.map(p=><article className="panel" key={p.id}><span className="avatar">{p.name.split(' ').map(n=>n[0]).join('')}</span><h3>{p.name}</h3><p>{p.trade} · Kaduna</p><Status>{p.status}</Status><div className="provider-stats"><span><Star size={15}/>{p.rating||'New'}</span><span>{p.jobs} jobs</span></div><Choice label={`Verification status for ${p.name}`} value={p.status} options={['Verified','Under review','Rejected']} onChange={s=>{if(!blocked)mutate({type:'provider',id:p.id,status:s})}}/><p className="fine-print">Provider verification status.</p></article>)}</div></section>}
 {tab==='Users'&&<section><div className="section-title"><h2>User accounts</h2><Users size={20}/></div><div className="panel"><Table><TableHeader><TableRow><TableHead>Name</TableHead><TableHead>Email</TableHead><TableHead>Role</TableHead><TableHead>Status</TableHead></TableRow></TableHeader><TableBody>{data.users.map(u=><TableRow key={u.id}><TableCell>{u.name}</TableCell><TableCell>{u.email}</TableCell><TableCell>{u.role}</TableCell><TableCell><Choice label={`Status for ${u.name}`} value={u.status} options={['Active','Suspended']} onChange={s=>{if(!blocked)mutate({type:'user',id:u.id,status:s})}}/></TableCell></TableRow>)}</TableBody></Table></div></section>}
 {tab==='Platform rates'&&<form className="panel rates-form" onSubmit={async e=>{e.preventDefault();await mutate({type:'rates',...rates})}}><div className="section-title"><h2>Platform rates</h2><Settings size={20}/></div><p>Save commission and service-charge settings.</p><div className="form-grid"><NumberField label="Commission (%)" value={rates.commission} onChange={n=>setRates({...rates,commission:n})} max={100} step={0.1}/><NumberField label="Repair service charge (%)" value={rates.service} onChange={n=>setRates({...rates,service:n})} max={100} step={0.1}/></div><Submit busy={blocked}>Save rates</Submit></form>}
 <Modal open={!!property} onClose={()=>setProperty(null)} title={property?.id?'Manage property':'Add a property'} description="Keep the property record and public listing up to date." wide>
 {property&&<form onSubmit={saveProperty} className="stack property-form"><div className="form-grid"><Field label="Listing title"><Input required maxLength={200} value={property.title} onChange={e=>setProperty({...property,title:e.target.value})}/></Field><Field label="Full address"><Input required maxLength={200} value={property.address} onChange={e=>setProperty({...property,address:e.target.value})}/></Field><Field label="Area"><Choice label="Property area" value={property.area} options={['Barnawa','Kawo','Malali','Ungwan Rimi','Sabon Tasha']} onChange={v=>setProperty({...property,area:v})}/></Field><Field label="Property status"><Choice label="Property status" value={property.status} options={['Available','Occupied','Under Maintenance']} onChange={v=>setProperty({...property,status:v})}/></Field><NumberField label="Monthly rent (₦) · 0 to unlist" value={property.rent} onChange={n=>setProperty({...property,rent:n})}/><NumberField label="Purchase price (₦)" value={property.price} onChange={n=>setProperty({...property,price:n})}/><NumberField label="Bedrooms" value={property.beds} onChange={n=>setProperty({...property,beds:n})} min={1} max={30}/><NumberField label="Bathrooms" value={property.baths} onChange={n=>setProperty({...property,baths:n})} min={1} max={30}/><NumberField label="Size (m²)" value={property.size} onChange={n=>setProperty({...property,size:n})} min={1}/><NumberField label="Construction year" value={property.year} onChange={n=>setProperty({...property,year:n})} min={1900} max={2100}/><Field label="Listing stage"><Choice label="Listing stage" value={property.stage} options={['Ready to move in','Under construction','Off plan']} onChange={v=>setProperty({...property,stage:v})}/></Field><NumberField label="Construction progress (%)" value={property.progress} onChange={n=>setProperty({...property,progress:n})} max={100}/></div><label className="check-row"><Switch checked={property.rto} onCheckedChange={v=>setProperty({...property,rto:v})}/><span>Rent-to-own eligible</span></label><Field label="About this home"><Textarea maxLength={3000} value={property.description} onChange={e=>setProperty({...property,description:e.target.value})}/></Field><Field label="Amenities (comma-separated)"><Input value={property.amenities.join(', ')} onChange={e=>setProperty({...property,amenities:e.target.value.split(',').map(v=>v.trim())})}/></Field><Field label="Floor plan summary"><Textarea maxLength={1000} value={property.floorPlan} onChange={e=>setProperty({...property,floorPlan:e.target.value})}/></Field><Field label="Warranty information"><Input maxLength={1000} value={property.warranty} onChange={e=>setProperty({...property,warranty:e.target.value})}/></Field><Submit busy={blocked}>Save property</Submit></form>}
 </Modal>
 <Modal open={report} onClose={()=>setReport(false)} title="Report an issue" description="A few details help the right provider prepare."><form onSubmit={saveReport} className="stack"><Field label="Which property?"><Choice value={reportForm.propertyId} label="Property for repair" onChange={v=>setReportForm({...reportForm,propertyId:v})} options={data.properties.filter(p=>role!=='Tenant'||p.id==='p6').map(p=>({value:p.id,label:p.address}))}/></Field><div className="form-grid"><Field label="What kind of issue?"><Choice label="Repair category" value={reportForm.category} options={['Plumbing','Electrical','General repairs']} onChange={v=>setReportForm({...reportForm,category:v,providerId:''})}/></Field><Field label="How urgent is it?"><Choice label="Urgency" value={reportForm.urgency} options={['Normal','Urgent']} onChange={v=>setReportForm({...reportForm,urgency:v})}/></Field></div><Field label="Describe the issue"><Textarea required minLength={10} maxLength={3000} rows={4} value={reportForm.description} onChange={e=>setReportForm({...reportForm,description:e.target.value})} placeholder="What’s wrong, and where in the property?"/></Field>{role!=='Tenant'&&<Field label="Provider (optional)"><Choice label="Book a provider" value={reportForm.providerId||'none'} onChange={v=>setReportForm({...reportForm,providerId:v==='none'?'':v})} options={[{value:'none',label:'Let the admin assign a provider'},...data.providers.filter(p=>p.status==='Verified'&&p.trade===reportForm.category).map(p=>({value:p.id,label:p.name}))]}/></Field>}<Submit busy={blocked}>Submit report</Submit></form></Modal>
 <Modal open={!!currentRepair} onClose={()=>setRepairId(null)} title={currentRepair?`${currentRepair.category} repair`:'Repair details'} description={currentRepair?pFor(currentRepair.propertyId)?.address:''}>
 {currentRepair&&<div className="stack"><div className="inline"><Status>{currentRepair.status}</Status><Status>{currentRepair.urgency}</Status></div><p>{currentRepair.description}</p><div className="repair-detail-meta"><div><span>Reported by</span><strong>{currentRepair.reportedBy}</strong></div><div><span>Job amount</span><strong>{money(currentRepair.amount)}</strong></div>{currentRepair.providerId&&<div><span>Provider</span><strong>{data.providers.find(p=>p.id===currentRepair.providerId)?.name}</strong></div>}{currentRepair.window&&<div><span>Visit window</span><strong>{currentRepair.window}</strong></div>}</div><h3>Status history</h3><ol className="status-history">{currentRepair.history.map((h,i)=><li key={i}><Check size={14}/><strong>{h.status}</strong><span>{shortDate(h.date)}</span></li>)}</ol>
 {currentRepair.status==='Reported'&&['Owner','Admin'].includes(role)&&<><Field label="Book a verified provider"><Choice label="Assigned provider" value={providerId||'none'} onChange={setProviderId} options={data.providers.filter(p=>p.status==='Verified'&&p.trade===currentRepair.category).map(p=>({value:p.id,label:p.name}))}/></Field>{!providerId&&<p className="notice">No verified provider is available for this category.</p>}<Button disabled={blocked||!providerId} onClick={()=>repairAction('Offered')}>Send booking request</Button>{role==='Admin'&&<Button variant="ghost" disabled={blocked} onClick={()=>repairAction('Closed')}>Close report without a booking</Button>}</>}
 {currentRepair.status==='Offered'&&role==='Provider'&&<><Field label="Choose a visit window"><Choice label="Visit window" value={visit} options={['Tomorrow, morning','Tomorrow, afternoon','In 2 days, morning']} onChange={setVisit}/></Field><Button disabled={blocked} onClick={()=>repairAction('Scheduled')}>Accept job</Button><Button variant="ghost" disabled={blocked} onClick={()=>repairAction('Reported')}>Decline job</Button></>}
 {currentRepair.status==='Scheduled'&&role==='Provider'&&<Button disabled={blocked} onClick={()=>repairAction('Awaiting confirmation')}>Mark job complete</Button>}
 {currentRepair.status==='Awaiting confirmation'&&['Owner','Admin'].includes(role)&&<><p className="notice">Confirming records repair payment completion.</p><Button disabled={blocked} onClick={()=>repairAction('Confirmed')}>Confirm completion</Button></>}
 {currentRepair.status==='Confirmed'&&<p className="notice success"><Check size={17}/>Completion confirmed. Payment recorded.</p>}
 </div>}
 </Modal>
 <Modal open={!!currentBill} onClose={()=>setBillId(null)} title="Record a payment" description={currentBill?`${currentBill.label} · ${pFor(currentBill.propertyId)?.address}`:''}>{currentBill&&<div className="stack"><div className="bill-amount">{money(currentBill.amount)}</div><p className="notice">This settles the bill in the workspace ledger.</p><Button disabled={blocked||currentBill.status!=='Due'} onClick={async()=>{if(await mutate({type:'payment',id:currentBill.id}))setBillId(null)}}>Confirm payment <Check size={17}/></Button></div>}</Modal>
 </main>
}
